export const ACTIONS = {
  GET_USER: "GET_USER",
  SET_USER: "SET_USER",
  UPDATE_USER: "UPDATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  REMOVE_USER: "REMOVE_USER",
  ADD_USER: "ADD_USER",
  PUT_USER: "PUT_USER",
};
